### ISSUE TITLE
Errors using with xcode 7 and swift 2

### ISSUE THREAD

**Issue by haansplosion** [maxep/DiscogsAPI#1]
Hi there maxine, trying to install the DiscogsAPI cocoapod into a project using Xcode Version 7.0 beta (7A121l)  swift 2, using a podfile containing the following:

platform :ios, '7.1'
pod 'DiscogsAPI'
use_frameworks!
xcodeproj '/path to my actual project.xcodeproj'

Ignoring the warnings (46), I get 29 errors before it gives up, as follows. Would really appreciate any help you could give me!

Command /usr/bin/ditto failed with exit code 1
(null): Directory not found for option '-F/Users/haansplosion/Library/Developer/Xcode/DerivedData/MyApp-gzjulonionecwzdqoybpxhoopwbi/Build/Intermediates/SwiftMigration/MyApp/Products/Debug-iphonesimulator/Pods'
(null): Linker command failed with exit code 1 (use -v to see invocation)
Command /bin/sh failed with exit code 23
MyAppUITests Group
Command /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
Command /usr/bin/ditto failed with exit code 1
(null): Linker command failed with exit code 1 (use -v to see invocation)
MyAppTests Group
(null): Linker command failed with exit code 1 (use -v to see invocation)

Pods-DiscogsAPI Group
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/ObjectMapping/RKObjectMapping.h
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/ObjectMapping/RKObjectMapping.h:23:9: Include of non-modular header inside framework module 'RestKit.RKObjectMapping'
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/ObjectMapping.h
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/ObjectMapping.h:24:9: Include of non-modular header inside framework module 'RestKit.ObjectMapping'
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/ObjectMapping.h:21:9: Could not build module 'RestKit'
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Network/RKHTTPRequestOperation.h
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Network/RKHTTPRequestOperation.h:21:9: Include of non-modular header inside framework module 'RestKit.RKHTTPRequestOperation'
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Network/RKHTTPRequestOperation.h:22:9: Include of non-modular header inside framework module 'RestKit.RKHTTPRequestOperation'
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Network/RKObjectManager.h
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Network/RKObjectManager.h:24:9: Include of non-modular header inside framework module 'RestKit.RKObjectManager'
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Vendor/LibComponentLogging/Core/lcl_RK.h
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Vendor/LibComponentLogging/Core/lcl_RK.h:134:1: Expected identifier
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Vendor/LibComponentLogging/Core/lcl_RK.h:134:1: Expected '}'
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Vendor/LibComponentLogging/Core/lcl_RK.h:130:31: Expected ';' after enum
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Support/lcl_config_components_RK.h:52:1: Initializer element is not a compile-time constant
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Support/lcl_config_components_RK.h:53:1: Initializer element is not a compile-time constant
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Support/lcl_config_components_RK.h:54:1: Initializer element is not a compile-time constant
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Support/lcl_config_components_RK.h:55:1: Initializer element is not a compile-time constant
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Support/lcl_config_components_RK.h:56:1: Initializer element is not a compile-time constant
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Support/lcl_config_components_RK.h:57:1: Initializer element is not a compile-time constant
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Support/lcl_config_components_RK.h:58:1: Initializer element is not a compile-time constant
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Support/lcl_config_components_RK.h:59:1: Initializer element is not a compile-time constant
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Support/lcl_config_components_RK.h:60:1: Initializer element is not a compile-time constant
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Support/lcl_config_components_RK.h:61:1: Initializer element is not a compile-time constant
/Users/haansplosion/Dropbox/GIT/MyApp/MyApp/Pods/RestKit/Code/Support/lcl_config_components_RK.h:62:1: Initializer element is not a compile-time constant
Too many errors emitted, stopping now

**Comment by maxep** [comment]
Hi @haansplosion 

This is actually a bug on RestKit, a [pull request](https://github.com/RestKit/RestKit/pull/2145) is in progress on there side. By the mean time you can try to set your podfile as:

``` ruby
platform :ios, '8.0'
use_frameworks!
pod 'RestKit', :git => 'https://github.com/RestKit/RestKit.git', :branch => 'seg-clang-modules'
pod 'DiscogsAPI'

xcodeproj '/path to my actual project.xcodeproj'
```

**Comment by haansplosion** [comment]
@maxep Thanks so much for looking into this for me!

Still getting much of the same errors on build though, as per below. (Please note I quickly created another project called DiscogsTest to try your fix)

/Users/haansplosion/Dropbox/GIT/DiscogsTest/DiscogsTest/Pods/RestKit/Code/ObjectMapping.h
/Users/haansplosion/Dropbox/GIT/DiscogsTest/DiscogsTest/Pods/RestKit/Code/ObjectMapping.h:21:9: Include of non-modular header inside framework module 'RestKit.ObjectMapping'
/Users/haansplosion/Dropbox/GIT/DiscogsTest/DiscogsTest/Pods/RestKit/Code/ObjectMapping.h:23:9: Could not build module 'RestKit'
/Users/haansplosion/Dropbox/GIT/DiscogsTest/DiscogsTest/Pods/RestKit/Code/ObjectMapping/RKObjectMapping.h
/Users/haansplosion/Dropbox/GIT/DiscogsTest/DiscogsTest/Pods/RestKit/Code/ObjectMapping/RKObjectMapping.h:24:9: Include of non-modular header inside framework module 'RestKit.RKObjectMapping'
/Users/haansplosion/Dropbox/GIT/DiscogsTest/DiscogsTest/Pods/RestKit/Code/Network/RKHTTPRequestOperation.h
/Users/haansplosion/Dropbox/GIT/DiscogsTest/DiscogsTest/Pods/RestKit/Code/Network/RKHTTPRequestOperation.h:21:9: Include of non-modular header inside framework module 'RestKit.RKHTTPRequestOperation'
/Users/haansplosion/Dropbox/GIT/DiscogsTest/DiscogsTest/Pods/RestKit/Code/Network/RKHTTPRequestOperation.h:22:9: Include of non-modular header inside framework module 'RestKit.RKHTTPRequestOperation'
/Users/haansplosion/Dropbox/GIT/DiscogsTest/DiscogsTest/Pods/RestKit/Code/Network/RKObjectManager.h
/Users/haansplosion/Dropbox/GIT/DiscogsTest/DiscogsTest/Pods/RestKit/Code/Network/RKObjectManager.h:25:9: Include of non-modular header inside framework module 'RestKit.RKObjectManager'

**Comment by haansplosion** [comment]
platform :ios, '8.0'
use_frameworks!
pod 'RestKit', :git => 'https://github.com/RestKit/RestKit.git', :branch => 'seg-clang-modules'
pod 'DiscogsAPI'

xcodeproj '/Users/Df/Dropbox/GIT/DiscogsTest/DiscogsTest.xcodeproj'

**Comment by haansplosion** [comment]
Sorry to bother you @maxep, but did you have any luck looking into this?

**Comment by maxep** [comment]
Hey! No not yet, I'm a bit busy with regular work. But I will have a look asap.

**Comment by haansplosion** [comment]
No problem. Thanks for looking!

**Comment by maxep** [comment]
Hi @haansplosion 

I'm very sorry, I can't find a way to use restkit as a dependency in a swift project... I will keep my head up on cocoapods and restkit, they might come out with upgrades that fixes the issue!

**Comment by nrivard** [comment]
This is actually a problem with `use_frameworks!` as the dependencies aren't modularized. If you aren't using additional Swift based cocoapods, you can safely remove that and everything will work.

**Comment by kpavankotesh** [comment]
Hey any luck with this? I am facing this issue and I have to use swift based cocoapods along with this. Please let us know if there is any progress regarding this

**Comment by nrivard** [comment]
@kpavankotesh the short answer is "no." At the moment, this cocoapod isn't setup to be a modularized framework which is required for `use_framework!`. It's just a collection of classes added to your project. I had written up a separate issue that would have addressed this (https://github.com/maxep/DiscogsAPI/issues/5) but it was closed. However, I do think it would be beneficial to make this a true module so I will see if I can get around to it on my branch and then make a PR for @maxep to approve.

**Comment by maxep** [comment]
Modularized framework should be straightforward with cocoapods but I guess this issue is related to Restkit dependency. I've not found a solution yet, any help will be appreciated :)

**Comment by maxep** [comment]
I've push a [framework](/maxep/DiscogsAPI/tree/framework) branch which includes a framework project and a Swift example. It's [Carthage compatible](https://github.com/Carthage/Carthage) but not with cocoapods yet.
You can find a built fw in the [Example-Swift](/maxep/DiscogsAPI/tree/framework/Example-Swift).
Let me know if you find any issue with it. I will then merge it to master and push a release with @nrivard additions.
