### ISSUE TITLE
Getting tons of keychain save failures on ios 10

### ISSUE THREAD

**Issue by nrivard** [maxep/DiscogsAPI#10]
(OSStatus) $13 = -34018
2016-09-19 20:19:39.116014 [38153:3716592] [] tcp_connection_cancel 6
2016-09-19 20:19:39.115 [38153:3690891] Unable to add credential with identifier "DGOAuthCredentialDiscogsAccount" (Error -34018)

I get the following error everytime i authorize via oauth on ios 10. The workaround noted here http://stackoverflow.com/questions/29740952/osstatus-error-code-34018 didn't work. Are you seeing tons of failures in new code compiled in xcode 8 on ios 10?

**Comment by maxep** [comment]
Hello @nrivard 
I dont see a tons of error on ios10, but I do reproduce this bug. Apparently, -34018 means `Internal error when a required entitlement isn't present.`, I tried to add entitlements by enabling the keychain sharing, it seems to workaround the error. But I dont know where that come from, other [threads](http://stackoverflow.com/a/28256591/4689795) says that it is raised only with debugger.

**Comment by nrivard** [comment]
Yep adding keychain sharing fixed my issue.
