### ISSUE TITLE
Rate-limiting ignored

### ISSUE THREAD

**Issue by nrivard** [maxep/DiscogsAPI#14]
My `BatchReleases` branch has some work to start to listen to rate-limiting but as it stands, DiscogsAPI just blasts the server with a million concurrent requests.

**Comment by maxep** [comment]
> DiscogsAPI just blasts the server with a million concurrent requests.

Well, I understand your point but this is not really helping. Please keep in mind this is an open source project that I maintain on my free time, I would be more likely to fix tickets reported with care.

That being said, I'm aware the rate limit is currently ignored and I've thought of a solution. My approach is to create an operation queue that throttle requests following the rate limit returned in responses. If we take the Discogs documentation values, api requests will be send each 250ms (240 per minute). This operation queue will be hold by the DGObjectManager shared across endpoints (except for images). I will push it on the `develop` branch for tests.

**Comment by nrivard** [comment]
@maxep I didn't mean to be flippant or offend. I care about this project too which is why I'm contributing time and code. So in general, keep up the good work ;)

On the technical side, for that to work you will have to pipe everything through that one operation queue again (as in unroll the per-endpoint queues that you added.) You may also want to kick concurrency down to a max of `1`. And you don't necessarily need to parcel operations out every 250ms, you can just look at the returned headers for a `429` response. Discogs will tell you when to retry as well (though I think it always says `60` seconds) in the `Retry-After` header. In my project, I just hit the API until i get back a `429` then I back off for 60 seconds.

**Comment by maxep** [comment]
Sorry for having misinterpreted. And I thank you for all your contributions :)

I agree to roll back to the unique operation queue, that operation queue will be settable (concurrency, suspented, etc...). But by default I would rather preserve the server and not exceeded that rate limit by throttling requests locally as suggested in the api documentation. That default behavior will slow down batch request (if batch < rate limite), but you will be able to change the operation queue at your convenience.
