### ISSUE TITLE
Do not return any Videos

### ISSUE THREAD

**Issue by ryonandesukedo** [maxep/DiscogsAPI#17]
In DGRelease class, 
- (NSArray *)videos{
return [_videos filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:@"embed == true"]];
}
is not return DGVideo list.

property of "videos" is Array of DGVideo, so predicateWithFormat can't be worked.

**Comment by maxep** [comment]
Yep that was a mistake :)

**Comment by ryonandesukedo** [comment]
@maxep 
;)
Should I send a pull request? or you will fix it??

**Comment by maxep** [comment]
If you have time for PR, I will do it otherwise. Thanks!

**Comment by ryonandesukedo** [comment]
@maxep 
Could you review my PR?
https://github.com/maxep/DiscogsAPI/pull/18

**Comment by maxep** [comment]
Fixed by #19
