### ISSUE TITLE
Fail to authenticate

### ISSUE THREAD

**Issue by yoasha** [maxep/DiscogsAPI#2]
Hi,
I am running DiscogsAPI example project, but I get lots of errors related to the authentication:

> Unable to fetch credential with identifier "DGOAuthCredentialDiscogsAccount" (Error -25300)
> 2015-09-06 13:46:55.846 DiscogsAPI[2341:33891457] T restkit.network:RKObjectRequestOperation.m:148 GET 'https://api.discogs.com/oauth/identity':
> request.headers={
>     Accept = "application/vnd.discogs.v2.discogs+json";
>     "Accept-Language" = "en-US;q=1";
>     Authorization = "Discogs key=My Discogs key, secret=My secret";
>     "User-Agent" = "DiscogsAPI/1 (iPhone; iOS 9.0; Scale/2.00)";
> }

In the Info.plist I replaced DISCOGS_APP_CONSUMER_Key with my app's actual consumer key, and DISCOGS_APP_CONSUMER_SECRET with my app's actual consumer secret. I need only Discogs Auth while OAuth is not required by my app.

Did I miss anything in my configuration?

BTW, I am running on XCode 7 Beta 6 on iPhone 6 Simulator.

**Comment by yoasha** [comment]
Okay, I found the issue and it's related both to XCode 7 and to the source code:
1. In Xcode 7, there is a need to add the following to Info.plist

> ```
> <key>NSAppTransportSecurity</key>
> <dict>
>     <key>NSAllowsArbitraryLoads</key>
>     <true/>
> </dict>
> ```
1. I remarked the code in DGSearchViewController->viewDidLoad since calling DGAuthViewController is not required when using 'Discogs Auth' only. (at least to my understanding..)

**Comment by maxep** [comment]
Hi @yoasha 

Thanks, good to know about XCode7.
You are right, the DGAuthViewController is an example on how to use OAuth. No need if you using Discogs Auth.
